name: Version and Release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version type'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
          - from-git
          - custom
        default: patch
        required: true
      new-version:
        description: 'Custom version (only used when version-type is custom)'
        required: false
      preid:
        description: 'Prerelease identifier'
        required: false

env:
  FORCE_COLOR: 3

permissions:
  contents: write

concurrency:
  group: npm-bump
  cancel-in-progress: true

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: true
        fetch-depth: 0
    - uses: actions/setup-node@v7
      with:
        node-version-file: package.json
    - run: npm i
    - run: npm test
    - name: Version and create GitHub release
      id: npm-bump
      uses: bcomnes/npm-bump@v3.0.4
      with:
        version-type: ${{ github.event.inputs['version-type'] }}
        new-version: ${{ github.event.inputs['new-version'] }}
        preid: ${{ github.event.inputs.preid }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish-cmd: npm run release
    - run: echo "$RELEASE_TAG"
      env:
        RELEASE_TAG: ${{ steps.npm-bump.outputs['release-tag'] }}
